version: '3.2'

services:
  server:
    build: .
    image: miner-proxy:latest
    restart: always
    ports:
      - 9999:9999
    command: miner-proxy -l :9999 -r asia2.ethermine.org:5555 -secret_key 12345 -sc

  client:
    build: .
    image: miner-proxy:latest
    restart: always
    ports:
      - 9999:9999
    command: miner-proxy -l :9999 -r 1.1.1.1:9999 -secret_key 12345 -sc -client